services:
  dys-server:
    image: atomy/dystopia-server:latest
    working_dir: /home/steamsrv/dystopia
    command: ./srcds_run -game dystopia -console -port 27015 +maxplayers 32 -ip 0.0.0.0 +map dys_vaccine +exec server.cfg +log on
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "27025:27015/tcp"
      - "27025:27015/udp"
    volumes:
      - ./server.cfg:/home/steamsrv/dystopia/dystopia/cfg/server.cfg
